spring.application.name=booking

#comment iwant to test locally
server.address=0.0.0.0


# Database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
# local MySQL database instead of environment variables
# spring.datasource.url=jdbc:mysql://localhost:3306/pethub
# spring.datasource.username=root
# spring.datasource.password=Ruhil@0409
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Ensure Hibernate handles schema creation securely if you don't run init scripts
spring.jpa.hibernate.ddl-auto=update


logging.file.name=C:/Users/USER/Documents/Code/PetHub - backend/log/booking.log
# Global log level
logging.level.root=INFO
# Your package logs more details
logging.level.com.innov.controller=DEBUG
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

spring.datasource.hikari.minimum-idle=5          
spring.datasource.hikari.maximum-pool-size=10    
spring.datasource.hikari.idle-timeout=30000      
spring.datasource.hikari.connection-timeout=30000 
spring.datasource.hikari.max-lifetime=1800000    
spring.datasource.hikari.pool-name=HikariPool-1

# EMAIL PURPOSE
# SMTP server host (Gmail's outgoing mail server in this case)
spring.mail.host=smtp.gmail.com
# Port number for sending email using STARTTLS (587 for Gmail)
spring.mail.port=587
# Your email address (used as the sender)
spring.mail.username=denielmustakim2303@gmail.com
# Your email password or app password (use an App Password for Gmail, not your regular password)
spring.mail.password=ezzm dkhd wrlk iyuo
# Enable SMTP authentication (true means you must log in with username and password)
spring.mail.properties.mail.smtp.auth=true
# Enable STARTTLS (adds encryption for secure email sending)
spring.mail.properties.mail.smtp.starttls.enable=true



#JWT
jwt.secret.access=2v9fGm4X7LzQ8tY3nC1hD6rR0sA9vB5w